# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build_docker CI

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'The version of the Docker image'
        required: true
        default: 'dev'
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and build
      run: |
        cd ./frontend
        npm install
        npm run build
        cp -r ./dist ../backend/
        cd ../backend
    - name: Build Image
      run: docker build -t registry.cn-shanghai.aliyuncs.com/dataease-v2/sqlbot:${{ inputs.image_version }} .
    - name: Login registry
      run: docker login registry.cn-shanghai.aliyuncs.com --username=划船不用桨_小白 --password=1qaz@WSX
    - name: Push Image
      run: docker push registry.cn-shanghai.aliyuncs.com/dataease-v2/sqlbot:${{ inputs.image_version }}
